# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push
on: push

jobs:
  # This workflow contains a single job called "build"
  linter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Sets up a Python environment for use
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Run flake8
        uses: jonasrk/flake8-action@master
        with:
          args: "--max-line-length=120"
